### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by routineLife1** [littlespray/StreamFlow#1]
nice work！when can we expect the code be public.

**Comment by littlespray** [comment]
Thank you very much for your interest in this work. We apologize that the submission process for StreamFlow hasn't gone very smoothly. However, regardless of the final review outcome, we have decided to release all the code and model weights in **3 months**.

**Comment by ChenNed** [comment]
Congrats on the acceptance at NeurIPS! Really looking forward to seeing the full implementation of this work! Hope you’ll release it soon!

**Comment by littlespray** [comment]
Thank you for your interest. Currently, both the code and the model weights have been made open source. We will package them into pip in the future to facilitate easier use by everyone.
