### ISSUE TITLE
how to get kitti multi frame data?

### ISSUE THREAD

**Issue by techshoww** [littlespray/StreamFlow#2]
When i run kitti multi frame evluation, the code occurs error: "FileNotFoundError: [Errno 2] No such file or directory: 'kitti-flow-2015/training/image_2/000000_08.png'"

**Comment by littlespray** [comment]
Thank you for your interest. Multi-frame KITTI data could be found [here](https://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=flow), the multi-view extension (14 GB), which contains more than 2 temporally adjacent images.
