### ISSUE TITLE
request for the “T+S+H+K” checkpoint

### ISSUE THREAD

**Issue by hanruijiang** [littlespray/StreamFlow#3]
Thanks for your excellent work.

Can you release the checkpoint that trained on “T+S+H+K”  dataset ?

Also, can you tell me which of the 4 weight files provided, trained on the most data, has the best performance?

Thanks a lot.

**Comment by littlespray** [comment]
Thank you for your attention. The checkpoints trained on "T+S+H+K" are streamflow-sintel.pth and streamflow-kitti.pth. The difference between them is that the latter has undergone more fine-tuning with more KITTI data. However, if you're referring to a checkpoint trained on a broader range of datasets, it would be streamflow-spring, which is fine-tuned on the Spring dataset based on streamflow-sintel.pth. Based on some prior observations, ``streamflow-things.pth`` and ``streamflow-spring.pth`` generally exhibit better generalization capabilities, as these two datasets contain much more samples.
